# Generated by Django 5.1.6 on 2025-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_remove_playlist_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
