# Generated by Django 5.0.3 on 2025-04-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_video_thumbnail_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='playlists.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist View',
                'verbose_name_plural': 'Playlist Views',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'playlist')},
            },
        ),
    ]
