# Generated by Django 5.1.6 on 2025-05-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlistview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
